# networks:
#   wordpress-network:
#     external: true
#   traefik-network:
#     external: true
 
# volumes:
#   mariadb-data:
#   wordpress-data:
#   traefik-certificates:
 
# services:
#   mariadb:
#     image: ${WORDPRESS_MARIADB_IMAGE_TAG}
#     volumes:
#       - mariadb-data:/var/lib/mysql
#     environment:
#       MARIADB_DATABASE: ${WORDPRESS_DB_NAME}
#       MARIADB_USER: ${WORDPRESS_DB_USER}
#       MARIADB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
#       MARIADB_ROOT_PASSWORD: ${WORDPRESS_DB_ADMIN_PASSWORD}
#     networks:
#       - wordpress-network
#     healthcheck:
#       test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
#       interval: 10s
#       timeout: 5s
#       retries: 3
#       start_period: 60s
#     restart: unless-stopped
 
#   wordpress:
#     image: ${WORDPRESS_IMAGE_TAG}
#     volumes:
#       - wordpress-data:/bitnami/wordpress
#     environment:
#       WORDPRESS_DATABASE_HOST: mariadb
#       WORDPRESS_DATABASE_PORT_NUMBER: 3306
#       WORDPRESS_DATABASE_NAME: ${WORDPRESS_DB_NAME}
#       WORDPRESS_DATABASE_USER: ${WORDPRESS_DB_USER}
#       WORDPRESS_DATABASE_PASSWORD: ${WORDPRESS_DB_PASSWORD}
#       WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
#       WORDPRESS_BLOG_NAME: ${WORDPRESS_BLOG_NAME}
#       WORDPRESS_FIRST_NAME: ${WORDPRESS_ADMIN_NAME}
#       WORDPRESS_LAST_NAME: ${WORDPRESS_ADMIN_LASTNAME}
#       WORDPRESS_USERNAME: ${WORDPRESS_ADMIN_USERNAME}
#       WORDPRESS_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
#       WORDPRESS_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
#       WORDPRESS_SMTP_HOST: ${WORDPRESS_SMTP_ADDRESS}
#       WORDPRESS_SMTP_PORT: ${WORDPRESS_SMTP_PORT}
#       WORDPRESS_SMTP_USER: ${WORDPRESS_SMTP_USER_NAME}
#       WORDPRESS_SMTP_PASSWORD: ${WORDPRESS_SMTP_PASSWORD}
#     networks:
#       - wordpress-network
#       - traefik-network
#     healthcheck:
#       test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
#       interval: 10s
#       timeout: 5s
#       retries: 3
#       start_period: 90s
#     # labels:
#     #   - "traefik.enable=true"
#     #   - "traefik.http.routers.wordpress.rule=Host(`${WORDPRESS_HOSTNAME}`)"
#     #   - "traefik.http.routers.wordpress.service=wordpress"
#     #   - "traefik.http.routers.wordpress.entrypoints=websecure"
#     #   - "traefik.http.services.wordpress.loadbalancer.server.port=8080"
#     #   - "traefik.http.routers.wordpress.tls=true"
#     #   - "traefik.http.routers.wordpress.tls.certresolver=letsencrypt"
#     #   - "traefik.http.services.wordpress.loadbalancer.passhostheader=true"
#     #   - "traefik.http.routers.wordpress.middlewares=compresstraefik"
#     #   - "traefik.http.middlewares.compresstraefik.compress=true"
#     #   - "traefik.docker.network=traefik-network"
#     restart: unless-stopped
#     depends_on:
#       mariadb:
#         condition: service_healthy

 


services:
  db:
    image: mysql:5.7
    container_name: database
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "myPassword" # Lösenord för root
      MYSQL_DATABASE: wordpress
      WORDPRESS_DB_HOST: db:3306
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: "myPassword"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    # ports:
    #   - 8000:80
    restart: always
    volumes:
      - wp_data:/var/www/html
    container_name: wordpress
    labels:
      - "traefik.enable=true" # Aktivera Traefik för denna tjänst
      - "traefik.http.routers.app.rule=Host(`wordpress.jarllindquist.com`)" # Matcha domänen
      - "traefik.http.routers.app.entrypoints=websecure" # Använd HTTPS EntryPoint
      - "traefik.http.routers.app.tls.certresolver=myresolver" # Koppla till certifikatlösaren
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: "myPassword"
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost:8000');
        define('WP_SITEURL', 'http://localhost:8000');
      WORDPRESS_ADMIN_USER: admin_user
      WORDPRESS_ADMIN_PASSWORD: admin_password
      WORDPRESS_ADMIN_EMAIL: admin@example.com
      WORDPRESS_LANGUAGE: sv_SE


volumes:
  db_data: {}
  wp_data: {}
